// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Berkman_Final_DMV.Models
{
    public partial class Driver
    {
        public Driver()
        {
            DriversInfractions = new HashSet<DriversInfraction>();
            Vehicles = new HashSet<Vehicle>();
        }

        public string DriverId { get; set; }
        public string DriverFirstName { get; set; }
        public string DriverLastName { get; set; }
        public string DriverSsn { get; set; }



        public virtual ICollection<DriversInfraction> DriversInfractions { get; set; }

        [JsonIgnore]
        public virtual ICollection<Vehicle> Vehicles { get; set; }

    }
}