// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Berkman_Final_DMV.Models
{
    public partial class DriversInfraction
    {
        public string InfractionId { get; set; }
        public string DriverId { get; set; }
        public string PersonnelId { get; set; }
        public string VehicleId { get; set; }
        public DateTime Date { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual Infraction Infraction { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}