// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Berkman_Final_DMV.Models
{
    public partial class Infraction
    {
        public Infraction()
        {
            DriversInfractions = new HashSet<DriversInfraction>();
        }

        public string InfractionId { get; set; }
        public string InfractionType { get; set; }

        public virtual ICollection<DriversInfraction> DriversInfractions { get; set; }
    }
}