// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Berkman_Final_DMV.Models
{
    public partial class Personnel
    {
        public Personnel()
        {
            DriversInfractions = new HashSet<DriversInfraction>();
        }

        public string PersonnelId { get; set; }
        public string PersonnelFirstName { get; set; }
        public string PersonnelLastName { get; set; }
        public string PersonnelTitle { get; set; }
        public string PersonnelUsername { get; set; }
        public string PersonnelPassword { get; set; }

        public virtual ICollection<DriversInfraction> DriversInfractions { get; set; }
    }
}